set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR mips)
set(TARGET_NAME hiwifi3)

set(TOOLCHAIN_ROOT /buildroot/hiwifi3/mips_32/linux-x86_64)
set(TOOLCHAIN_ABI mipsel-openwrt-linux-uclibc)

set(CMAKE_SYSROOT ${TOOLCHAIN_ROOT}/${TOOLCHAIN_ABI})

set(CMAKE_C_COMPILER ${TOOLCHAIN_ROOT}/bin/${TOOLCHAIN_ABI}-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_ROOT}/bin/${TOOLCHAIN_ABI}-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
