#ifndef __BDT_CONNECTION_MODULE_IMPL__
#define __BDT_CONNECTION_MODULE_IMPL__
#include "./PackageConnection/LedbatCc.imp.inl"
#include "./PackageConnection/RecvQueue.imp.inl"
#include "./PackageConnection/SendQueue.imp.inl"
#include "./PackageConnection/PackageConnection.imp.inl"
#include "./Connection.imp.inl"
#include "./ConnectionManager.imp.inl"
#include "./StreamConnection.imp.inl"
#endif //__BDT_CONNECTION_MODULE_IMPL__